# Generated by Django 2.2.7 on 2020-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncourse', '0002_auto_20200311_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
