# Generated by Django 2.2.7 on 2020-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncourse', '0003_details_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
