# Generated by Django 2.2.7 on 2020-03-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncourse', '0004_details_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncourse.Course')),
            ],
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
