# Generated by Django 2.2.7 on 2020-03-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncourse', '0005_auto_20200313_0155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
