# Generated by Django 3.0.4 on 2020-03-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncourse', '0007_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='\\oncourse\templates\\oncourse', upload_to=''),
            preserve_default=False,
        ),
    ]
